blog/urls.py
from django.urls import path

from . import views


app_name = 'blog'

urlpatterns = [
    path('', views.index, name='index'),
    path('detail/<int:pk>', views.detail, name='detail'),
    path('category/<int:pk>', views.category_filter, name='category_filter'),
    path('tag/<int:pk>', views.tag_filter, name='tag_filter'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')), 
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

blog/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class ParentCategory(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=255)
    parent = models.ForeignKey(ParentCategory, verbose_name='親カテゴリ', on_delete=models.PROTECT)

    def __str__(self):
        return self.name


class PostManager(models.Manager):

    def get_queryset(self):
        return super().get_queryset().select_related('category__parent').prefetch_related('tag')


class Post(models.Model):
    title = models.CharField('タイトル', max_length=255)
    main_text = models.TextField('本文', null=True, blank=True)
    category = models.ForeignKey(Category, verbose_name='カテゴリ', on_delete=models.PROTECT)
    tag = models.ManyToManyField(Tag, verbose_name='タグ', blank=True)

    objects = PostManager()

blog/views.py
from django.views import generic
from django.shortcuts import render
from django.shortcuts import get_object_or_404

from .models import Post, Category, Tag


def index(request):
    context = {
        'posts': Post.objects.all(),
        'tags': Tag.objects.all(),
        'categorys': Category.objects.all().prefetch_related('post_set'),
        # 'categorys': Category.objects.all(),
    }
    return render(request, 'blog/index.html', context)


def detail(request, pk):
    return render(request, 'blog/detail.html', {'post': get_object_or_404(Post, pk=pk)})


def category_filter(request, pk):
    return render(request, 'blog/category_filter.html', {'category': get_object_or_404(Category, pk=pk)})


def tag_filter(request, pk):
    return render(request, 'blog/tag_filter.html', {'tag': get_object_or_404(Tag, pk=pk)})

blog/templates/blog/category_filter.html
<body>
  
  <h1>日記</h1>
  <p>{{ category }}</p>
  <ul>
    {% for post in category.post_set.all %}
  <li>
    {{ post.title }} <br />
    親カテゴリ {{ post.category.parent.name }}<br>
    子カテゴリ {{ post.category.name }}
    <br>
    <br>
    <ul>
      タグ
      {% for tag in post.tag.all %}
      <li>
        {{ tag.name }}
      </li>
      {% empty %}
      <p>タグはありません</p>
      {% endfor %}
    </ul><br>
    <a href="{% url 'blog:detail' post.id %}">記事を読む</a>
  </li>
  <br/>
  <br/>
  {% empty %}
  <p>まだ記事がありません。</p>
  {% endfor %}
</ul>

</body>

blog/templates/blog/detail.html
<html>
  <head>
    <title></title>
  </head>
  <body>
    <h1>{{post.title}}</h1>
    <div>子カテゴリ：{{post.category.name}}</div>
    <ul>
    タグ
    {% for tag in post.tag.all %}
      <li>
        {{ tag.name }}
      </li>
      {% empty %}
      <p>タグはありません</p>
      {% endfor %}
    </ul>
    <p>{{post.main_text}}</p>
  </body>
</html>

blog/templates/blog/index.html
  <head>
    <title></title>
  </head>
  <body>
    <h1>日記</h1>
    <ul>
      {% for post in posts %}
      <li>
        {{ post.title }} <br />
        親カテゴリ {{ post.category.parent.name }}<br>
        子カテゴリ <a href="{% url 'blog:category_filter' post.category.id %}">{{ post.category.name }}</a>
        <br>
        <br>  
        <ul>
          タグ
          {% for tag in post.tag.all %}
            <li>
              <a href="{% url 'blog:tag_filter' tag.id %}">{{ tag.name }}</a>
            </li>
          {% empty %}
            <p>タグはありません</p>
          {% endfor %}
        </ul>
        <br>
        <a href="{% url 'blog:detail' post.id %}">記事を読む</a>
      </li>
      <br/>
      <br/>
      {% empty %}
        <p>まだ記事がありません。</p>
      {% endfor %}
    </ul>
    <br/>
    <h1>タグ一覧</h1>
    <ul>
      {% for tag in tags %}
        <li>
          <a href="{% url 'blog:tag_filter' tag.id %}">{{ tag.name }}</a>
        </li>
      {% empty %}
        <p>登録されているタグはありません</p>
      {% endfor %}
      <br>
      <br>
    </ul>
  </body>

blog/templates/blog/tag_filter.html
<body>
  
  <h1>タグ</h1>
  <p>{{ tag }}</p>
  <ul>
    {% for post in tag.post_set.all %}
  <li>
    {{ post.title }} <br>
    親カテゴリ {{ post.category.parent.name }}<br>
    子カテゴリ
    <a href="{% url 'blog:category_filter' post.category.id %}">{{ post.category.name }}</a>
    <br>
    <br>
    <ul>
      タグ 
      {% for tag in post.tag.all %}
        <li>
          {{ tag.name }}
        </li>
      {% empty %}
        <p>タグはありません</p>
      {% endfor %}
    </ul>
    <br />
    <a href="{% url 'blog:detail' post.id %}">記事を読む</a>
  </li>
  <br />
  {% empty %}
  <p>まだ記事がありません。</p>
  {% endfor %}
</ul>
<br />

</body>